"""Pre-registered single-fault mutant definitions for MiniForms."""


MUTANTS = [
    {"id": "M01", "form": "Registration", "target": "registration", "category": "Partition", "requirement": "REG-R2", "description": "Email domain no longer needs a dot", "witness_test_id": "DT-REG-03", "old": r"const EMAIL_PATTERN = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;", "new": r"const EMAIL_PATTERN = /^[^\s@]+@[^\s@]+$/;"},
    {"id": "M02", "form": "Registration", "target": "registration", "category": "Partition", "requirement": "REG-R3", "description": "Non-integer age is accepted", "witness_test_id": "EP-REG-07", "old": "if (!Number.isInteger(age) || age < 18 || age > 60) {", "new": "if (age < 18 || age > 60) {"},
    {"id": "M03", "form": "Registration", "target": "registration", "category": "Boundary", "requirement": "REG-R1", "description": "Minimum username uses > 5 instead of >= 5", "witness_test_id": "BVA-REG-USER-02", "old": "if (username.length < 5 || username.length > 15) {", "new": "if (username.length <= 5 || username.length > 15) {"},
    {"id": "M04", "form": "Registration", "target": "registration", "category": "Boundary", "requirement": "REG-R3", "description": "Maximum age uses < 60 instead of <= 60", "witness_test_id": "BVA-REG-AGE-05", "old": "if (!Number.isInteger(age) || age < 18 || age > 60) {", "new": "if (!Number.isInteger(age) || age < 18 || age >= 60) {"},
    {"id": "M05", "form": "Registration", "target": "registration", "category": "Decision-rule", "requirement": "REG-R5", "description": "Password confirmation is ignored in the acceptance decision", "witness_test_id": "EP-REG-10", "old": "return { accepted: errors.length === 0, errors };", "new": "return { accepted: errors.filter((error) => error !== \"Password and confirmation must match.\").length === 0, errors };"},
    {"id": "M06", "form": "Registration", "target": "registration", "category": "Decision-rule", "requirement": "REG-R1", "description": "Username invalid-range conditions use AND instead of OR", "witness_test_id": "EP-REG-02", "old": "if (username.length < 5 || username.length > 15) {", "new": "if (username.length < 5 && username.length > 15) {"},
    {"id": "M07", "form": "Shipping", "target": "shipping", "category": "Partition", "requirement": "SHIP-input", "description": "Unknown customer type is accepted", "witness_test_id": "EP-SHIP-02", "old": "if (![\"regular\", \"vip\"].includes(customerType)) {", "new": "if (false) {"},
    {"id": "M08", "form": "Shipping", "target": "shipping", "category": "Partition", "requirement": "SHIP-input", "description": "Unknown shipping region is accepted", "witness_test_id": "EP-SHIP-03", "old": "if (![\"local\", \"remote\"].includes(region)) {", "new": "if (false) {"},
    {"id": "M09", "form": "Shipping", "target": "shipping", "category": "Boundary", "requirement": "SHIP-R3", "description": "Coupon threshold uses > 500,000 instead of >=", "witness_test_id": "BVA-SHIP-COUPON-02", "old": "couponStatus === \"valid\" && orderValue >= 500_000", "new": "couponStatus === \"valid\" && orderValue > 500_000"},
    {"id": "M10", "form": "Shipping", "target": "shipping", "category": "Boundary", "requirement": "SHIP-R5", "description": "Free-shipping threshold uses > 800,000 instead of >=", "witness_test_id": "BVA-SHIP-FREE-02", "old": "region === \"local\" && orderValue >= 800_000", "new": "region === \"local\" && orderValue > 800_000"},
    {"id": "M11", "form": "Shipping", "target": "shipping", "category": "Decision-rule", "requirement": "SHIP-R2", "description": "VIP discount eligibility uses OR instead of AND", "witness_test_id": "BVA-SHIP-VIP-01", "old": "customerType === \"vip\" && orderValue >= 1_000_000", "new": "customerType === \"vip\" || orderValue >= 1_000_000"},
    {"id": "M12", "form": "Shipping", "target": "shipping", "category": "Decision-rule", "requirement": "SHIP-R4", "description": "Both discounts are added instead of selecting the highest", "witness_test_id": "EP-SHIP-08", "old": "const discountRate = Math.max(vipDiscount, couponDiscount);", "new": "const discountRate = vipDiscount + couponDiscount;"},
    {"id": "M13", "form": "Loan", "target": "loan", "category": "Partition", "requirement": "LOAN-R1", "description": "Non-integer age is accepted", "witness_test_id": "EP-LOAN-04", "old": "if (!Number.isInteger(age) || age < 21 || age > 60) {", "new": "if (age < 21 || age > 60) {"},
    {"id": "M14", "form": "Loan", "target": "loan", "category": "Partition", "requirement": "LOAN-R3", "description": "Non-integer credit score is accepted", "witness_test_id": "EP-LOAN-08", "old": "if (!Number.isInteger(creditScore) || creditScore < 650 || creditScore > 850) {", "new": "if (creditScore < 650 || creditScore > 850) {"},
    {"id": "M15", "form": "Loan", "target": "loan", "category": "Boundary", "requirement": "LOAN-R2", "description": "Minimum income uses > 15,000,000 instead of >=", "witness_test_id": "BVA-LOAN-INCOME-02", "old": "monthlyIncome < 15_000_000", "new": "monthlyIncome <= 15_000_000"},
    {"id": "M16", "form": "Loan", "target": "loan", "category": "Boundary", "requirement": "LOAN-R5", "description": "Maximum loan uses < 10x income instead of <=", "witness_test_id": "BVA-LOAN-MAX-02", "old": "requestedLoan > monthlyIncome * 10", "new": "requestedLoan >= monthlyIncome * 10"},
    {"id": "M17", "form": "Loan", "target": "loan", "category": "Decision-rule", "requirement": "LOAN-R4", "description": "Employment condition is ignored", "witness_test_id": "EP-LOAN-09", "old": "if (employmentStatus !== \"employed\") {", "new": "if (false) {"},
    {"id": "M18", "form": "Loan", "target": "loan", "category": "Decision-rule", "requirement": "LOAN-R5", "description": "Loan positivity and upper-limit checks use AND instead of OR", "witness_test_id": "EP-LOAN-10", "old": "requestedLoan <= 0 || requestedLoan > monthlyIncome * 10", "new": "requestedLoan <= 0 && requestedLoan > monthlyIncome * 10"},
]
